### ISSUE TITLE
No documentation - no idea where to start

### ISSUE THREAD

**Issue by DLPB2** [richgel999/bc7enc_rdo#13]
Hi,

I am trying to use this to load and save from a filename

Loading:
BC7 dds input file from hard drive (with a filename) - output to RGBA raw uncompressed mem stream.

Example: Loadbc7("c:\myfile.dds");

Saving:
RGBA raw uncompressed mem stream to BC7 dds output file (a filename - height and width need specifying to the output file)
Savebc7("c:\myfile.dds", 512, 1024);

Do you have any working examples of this?

**Comment by richgel999** [comment]
Hi,
I would start by checking out Microsoft DDS documentation:
https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dx-graphics-dds-pguide

DDS is supported by numerous tools (like AMD Compressonator, Renderdoc, etc.) and libraries (like freeimage). 

You can also find several DDS readers/writers on github, for example:
https://github.com/Microsoft/DirectXTK/wiki/DDSTextureLoader
