### ISSUE TITLE
Patents?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [richgel999/bc7enc_rdo#14]
Do any of the algorithms here require me to license some patent?

**Comment by richgel999** [comment]
I (and my company, Binomial) have zero patents on anything. 

Compressed textures have been supported by various graphics API's for decades:
https://docs.microsoft.com/en-us/windows/win32/direct3d11/texture-block-compression-in-direct3d-11

Deflate is patent-free - see the zlib documentation.

As for GPU textures: if you ship *software* that uses compressed textures under Windows, OSX, or consoles, then no - Microsoft, Apple, Sony, Nintendo, etc. have each acquired the relevant licenses for the various compressed texture formats. These licenses enable software creators to use these textures on these platforms. If you're working on GPU hardware the story may be different, but it's doubtful you are. Under Linux you are really on your own.

**Comment by devshgraphicsprogramming** [comment]
> I (and my company, Binomial) have zero patents on anything.
> 
> Compressed textures have been supported by various graphics API's for decades: https://docs.microsoft.com/en-us/windows/win32/direct3d11/texture-block-compression-in-direct3d-11
> 
> Deflate is patent-free - see the zlib documentation.
> 
> As for GPU textures: if you ship _software_ that uses compressed textures under Windows, OSX, or consoles, then no - Microsoft, Apple, Sony, Nintendo, etc. have each acquired the relevant licenses for the various compressed texture formats. These licenses enable software creators to use these textures on these platforms. If you're working on GPU hardware the story may be different, but it's doubtful you are. Under Linux you are really on your own.

The same patents cover both encoding and decoding?

AFAIK a GPU hardware vendor has have to had licensed the patent and the BC textures are decoded on the HW so we're always covered, but producing the actual (encoding) textures would be covered or not?
