### ISSUE TITLE
Possible to have an unified api for both ISPC and CPU

### ISSUE THREAD

**Issue by fire** [richgel999/bc7enc_rdo#5]
I was wondering if it was possible to keep the same API as ispc for the cpu edition.

It's mixed currently.

**Comment by richgel999** [comment]
Do you mean unify the parameters in rdo_bc_params, so that bc7e.ispc and bc7enc.cpp take the same parameters?

**Comment by fire** [comment]
That's one of them.

**Comment by fire** [comment]
I was able to work past this.
